image: trenpixster/elixir:latest

services:
  - postgres:latest

variables:
  DATABASE_URL: "psql://postgres:postgres@postgres/test_test"
  MIX_ENV: "test"

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate

mix:
  script:
  - mix test