version: "3.4"

services:
  app:
    build:
      context: .
      args:
        ENV: test
      target: app
    command: sh -c "mix deps.get && mix ecto.migrate && mix test.watch --stale"
    depends_on:
      - db
    environment:
      DATABASE_URL: "psql://klausurarchiv_test:klausurarchiv@db/klausurarchiv_test"
      SECRET_KEY_BASE: vCYwlWedpDhj5OEFaMqhnNDzO+rT/AQwRRTu7NwidjASFI4js35VYYF0x5ARb+Uc
      LIVE_VIEW_SALT: pwCwZuECFRuIQKmFS1mblLgc68jg5dOw
  assets:
    build:
      context: .
      target: assets
      args:
        ENV: dev
    command: sh -c "yarn install && yarn run dev"

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: klausurarchiv_test
      POSTGRES_PASSWORD: klausurarchiv
      POSTGRES_DB: klausurarchiv_test
