version: "3.4"

services:
  app:
    build:
      context: .
      args:
        ENV: dev
      target: app
    command: sh -c "mix deps.get && mix ecto.migrate && mix phx.server"
    depends_on:
      - db
      - sync
    environment:
      DATABASE_URL: "psql://klausurarchiv:klausurarchiv@db/klausurarchiv"
      S3_BUCKET: "exam-files"
      AWS_ACCESS_KEY_ID: "accesskey"
      AWS_SECRET_ACCESS_KEY: "secretkey"
      HOST: "http://localhost:4000"
      SMTP_FROM_ADDRESS: "admin@fachschaft-wiwi.ms"
    ports:
      - "4000:4000"

  assets:
    build:
      context: .
      target: assets
      args:
        ENV: dev
    depends_on:
      - sync
    ports:
      - "4001:4001"
    command: sh -c "yarn install && yarn run watch"

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: klausurarchiv
      POSTGRES_PASSWORD: klausurarchiv
      POSTGRES_DB: klausurarchiv
    ports:
      - "15432:5432"

  minio:
    image: minio/minio:latest
    entrypoint: "sh"
    command: "-c 'mkdir -p /data/exam-files && minio server /data --console-address :9001'"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: accesskey
      MINIO_SECRET_KEY: secretkey
