version: "3.4"

services:
    adminer:
        image: adminer
        ports:
          - 8080:8080
        environment:
          ADMINER_DEFAULT_SERVER: localhost
          ADMINER_DESIGN: pepa-linha
