version: "3.4"

services:
  app:
    build:
      context: .
      args:
        ENV: dev
      target: app
    command: sh -c "mix deps.get && mix ecto.migrate && mix phx.server"
    depends_on:
      - db
      - sync
    environment:
      DATABASE_URL: "psql://immobook:immobook@db/immobook"
    ports:
      - "4000:4000"

  # assets:
  #   build:
  #     context: .
  #     target: assets
  #     args:
  #       ENV: dev
  #   depends_on:
  #     - sync
  #   ports:
  #     - "4001:4001"
  #   command: sh -c "yarn install && yarn run dev"

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: immobook
      POSTGRES_PASSWORD: immobook
      POSTGRES_DB: immobook
    ports:
      - "15432:5432"
