version: "3.4"

services:
    adminer:
        image: adminer
        ports:
          - 8080:8080
        environment:
          ADMINER_DEFAULT_SERVER: db
          ADMINER_DESIGN: dracula
          ADMINER_DEFAULT_DB_DRIVER: psql
          ADMINER_DEFAULT_DB_NAME: klausurarchiv
