version: "3.4"

services:
  app:
    build:
      context: .
    environment:
      DATABASE_URL: "psql://immobook:immobook@db/immobook"
      PORT: "4000"
    depends_on:
      - db
    ports:
      - "4000:4000"

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: immobook
      POSTGRES_PASSWORD: immobook
      POSTGRES_DB: immobook
    ports:
      - "15432:5432"

volumes:
  app:
