import Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# KlausurarchivWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.

# Please config your environment variables as following:

# LIVE_VIEW_SALT=<salt> (You can generate one by calling: mix phx.gen.secret)
# PORT=4000
# HOST=example.com
# SECRET_KEY_BASE=<salt> (You can generate one by calling: mix phx.gen.secret)

config :klausurarchiv, KlausurarchivWeb.Endpoint,
  server: true,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Please config your environment variables as following:

# SENTRY_DSN=https://randomnumberstring@random.ingest.sentry.io/random

config :sentry,
  dsn: {:system, "SENTRY_DSN"},
  enable_source_code_context: true,
  root_source_code_path: File.cwd!(),
  included_environments: [:prod, :staging]

# Please config your environment variables as following:

# APPSIGNAL_PUSH_API_KEY = 123456789

config :appsignal, :config,
  otp_app: :klausurarchiv,
  name: "Klausurarchiv",
  env: Mix.env(),
  active: true,
  running_in_container: true

config :logger,
  backends: [:console, Sentry.LoggerBackend]
