name: publish-image
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - name: login-github-packages
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: "docker.pkg.github.com"
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
    - name: checkout-repo
      uses: actions/checkout@master
    - run: echo "$PROD_SECRET_EXS" > "config/prod.secret.exs"
      env:
        PROD_SECRET_EXS: ${{ secrets.PROD_SECRET_EXS }}
    - name: build-image
      run: docker build --pull -t docker.pkg.github.com/fs-wiwi-ms/klausurarchiv/klausurarchiv .
    - name: push-image-master
      run: docker push docker.pkg.github.com/fs-wiwi-ms/klausurarchiv/klausurarchiv
      if: github.ref == 'refs/heads/master'
    - name: push-image-non-master
      run: docker push docker.pkg.github.com/fs-wiwi-ms/klausurarchiv/klausurarchiv:$GITHUB_SHA
      if: github.ref != 'refs/heads/master'
      env:
        GITHUB_SHA: ${{ github.sha }}
