name: build
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - name: install_docker
      # run: docker build --pull -t Klausurarchiv .
      uses: actions/docker/cli@master
      with:
        args: build --pull -t tbho/klausurarchiv .
