name: build
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - run: echo "$PROD_SECRET_EXS" > "config/prod.secret.exs"
      env:
        PROD_SECRET_EXS: ${{ secrets.PROD_SECRET_EXS }}
    - name: build_docker_container
      uses: actions/docker/cli@master
      with:
        args: build --pull -t tbho/klausurarchiv .
